[build]
# This tells Netlify: "The website is already inside this folder"
publish = "build/web"

# This dummy command prevents Netlify from trying to run "flutter build"
command = "echo 'Serving Pre-built Flutter App'"

[[redirects]]
# This fixes the "Refresh Page" error on Flutter apps
from = "/*"
to = "/index.html"
status = 200